POST {{host}}/attributes/atk-speed/decidueye
Content-Type: application/json

{
  "buffs": [
    {
      "name": "boost",
      "stack": 4
    },
    {
      "name": "Razor Leaf"
    },
    {
      "name": "Help hands"
    }
  ],
  "items": [
    {
      "name": "Muscle Band",
      "level": 30
    }, {
      "name": "scarf",
      "level": 30
    }
  ]
}
