POST {{host}}/attributes/atk-speed/decidueye
Content-Type: application/json

{
  "buffs": [{
    "name": "boost",
    "stack": 4
  }],
  "items": [{
    "name": "Muscle Band",
    "level": 30
  }, {
    "name": "scarf",
    "level": 30
  }]
}
