POST {{host}}/attributes/atk-speed/aegislash
Content-Type: application/json

{
  "buffs": [{
    "name": "stanceForm",
    "form": "sword"
  }, {
    "name": "stanceChangeTemporary"
  }],
  "items": [{
    "name": "Muscle Band",
    "level": 30
  }]
}
