export enum PokemonNamesEnum {
  absol = 'absol',
  'mr.mime' = 'mr.mime',
  alolaNinetales = 'alolaNinetales',
  aegislash = 'aegislash',
  azumarill = 'azumarill',
  blastoise = 'blastoise',
  blissey = 'blissey',
  buzzwole = 'buzzwole',
  cinderace = 'cinderace',
  delphox = 'delphox',
  slowbro = 'slowbro',
  cramorant = 'cramorant',
  decidueye = 'decidueye',
  eldegoss = 'eldegoss',
  greninja = 'greninja',
  machamp = 'machamp',
  mamoswine = 'mamoswine',
  tyranitar = 'tyranitar',
  wigglytuff = 'wigglytuff',
}
